#esse é quem gerencia os arquivos em markdown
#esse arquivo .yml esta ligado ao netlify-cms

###OBSERVACAO
###PARACE QUE ESSA MERDA DA PAU SE NO GITHUG ESTA
###  PRIVATE...NAO SOBE FOTOS PELO NETLIFY 
###   DA ERRO DE API BLALALA

###OBSERVACAO2
### NA HORA DE CRIAR ESSA MERDA ESSE TEM
### UMA FRESCURAR DE COMECANDO DA ESQUERDA MESMO
### E DE ESPACAMENTO NA LINHA ABAIXO, POR EXEMPLO,
##  ABAIXO DO BACKEND, QUE SE TIVER A MAIS DA PAU
### QUANDO NO ABRIR O LINK NO BROWSER DO NETLIFY.

#backend do meu site
#quem vai manter
#onde executara
#qual o repositorio dento de onde vai manter
backend:
    name: github
    branch: master
    repo: jaieme/0003-blog-md

#media - qdo sobe uma imagem
#public - qdo faz um build do site
media_folder: static/img
public_folder: /img

#organizar dados - collections
##OBS da pau de netlify can upload photo
##para resolver precisa habilitar o 
##git-gateway dentro do site do netlify (e la logar 
##      com a senha do github) e dentro a secao sites
##      identity...ali encontra. Sem isso nao vai fotos!!
## alem do acima ainda tem mais coisa, pq nao funcionou
## ainda.
##https://www.freecodecamp.org/news/how-to-build-a-blog-with-gatsby-and-netlify-cms/
##https://blog.bitsrc.io/use-netlify-cms-with-gatsby-blogs-8bb73ab2e0cf
##https://www.gatsbyjs.com/docs/how-to/sourcing-data/sourcing-from-netlify-cms/
##https://www.gatsbyjs.com/tutorial/blog-netlify-cms-tutorial/
##https://www.netlifycms.org/docs/gatsby/



collections:
  - name: 'author' #esse campo aparece na url /collections/author
    label: 'Autores' # esse nome aparece nuns botoes, dentro do ambiente Netlify
    folder: 'src/authors'
    create: true
    slug: '{{slug}}'
    path: '{{slug}}/index'
    fields:
        - { label: 'Nome', name: 'title', widget: 'string' }
        - { label: 'Path', name: 'path', widget: 'string' }
        - { label: 'Avatar', name: 'avatar', widget: 'image' }
        - { label: 'Bio', name: 'body', widget: 'markdown' }


## a partir daqui para baixo foi tudo colocado pensando
## nos files markdown feitos por mim e nas pastas dentro de
## /scr/components/..
## eis que ele abriu outra collections e usou como referencia
## o cabeçalho dos arquivos md e as informações deles, cujas
## quais se repetem em todos ou na maioria.
## exemplo abaixo:
##  path: '/blog/minha-pagina'
##  title: 'FOTO - Minha página - info do campo title do Arquivo .MD'
##  description: 'info no campo description do Arquivo .MD'
##  categories: 'categoria'
##  price: 10
##  banner: './img1.jpg'

  - name: 'blog'
    label: 'Blog Post'
    folder: 'src/content'
    create: true
    slug: '{{slug}}'
    path: '{{slug}}/index'
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Path', name: 'path', widget: 'string' }
      #- { label: 'Categoria', name: 'categories', widget: 'string' }
      #- { label: 'Preço', name: 'price', widget: 'float' }
      - { label: 'Banner', name: 'banner', widget: 'image' }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }








